retry on memcached ConnectTimeoutError
bukalapak/ottoman pull request #13
Opened 2021-02-05 05:58 UTC by hajarbleh

Retry on memcached ConnectTimeoutError. Default retry is 3 times

2021-02-08 04:33 UTC, subosito requested changes

2021-02-08 04:33 UTC, subosito commented on memcache/memcache.go
> +	for i := 0; i < c.option.MaxAttempt; i++ {
block semacam ini sebaiknya dipindah jadi method tersendiri @hajarbleh, biar ga duplicate di banyak tempat.

```go
func (c *Memcache) retry(fn func() error) error {
        for i := 0; i < c.option.MaxAttempt; i++ {
                err := fn()

                if !timeoutError(err) {
                        return err
                }
        }

        return nil
}
```

Sample usage:

```go
func (c *Memcache) Read(key string) ([]byte, error) {
....
        fn := func() error {
                item, err = c.client.Get(key)
                return err
        }

        err = c.retry(fn)
...
```

2021-02-08 05:19 UTC, hajarbleh commented on memcache/memcache.go
> +	for i := 0; i < c.option.MaxAttempt; i++ {
Kemarin saya bikin spt ini mas awalnya, tapi sempet ada kendala di testingnya cuma saya lupa capture. Saya coba bikin begini lagi dulu

2021-02-09 14:36 UTC, galihputera approved these changes

2021-02-10 02:32 UTC, vny1422 commented on memcache/memcache.go
> +func NewWithClient(mc MemcacheClient, option Option) *Memcache {
api documentation function ini dikasih ya

2021-02-10 02:46 UTC, hajarbleh commented on memcache/memcache.go
> +func NewWithClient(mc MemcacheClient, option Option) *Memcache {
Added

2021-02-10 02:46 UTC, hajarbleh commented on memcache/memcache.go
> +	for i := 0; i < c.option.MaxAttempt; i++ {
Done

2021-02-10 07:13 UTC, pascalmail commented on memcache/memcache.go
> +type MemcacheClient interface {
Ini tambahin dokumentasinya juga ya, interface-nya buat apa.

2021-02-11 03:32 UTC, budipang approved these changes

2021-02-11 06:06 UTC, subosito approved these changes

2021-02-11 06:22 UTC, merged