[CORE-2196] custom marshaler and unmarshaler for type alias json.Number
bukalapak/ottoman pull request #15
Opened 2021-04-28 14:34 UTC by agriardyan

We discovered that the unmarshal behavior of json.Number changed. On go1.13, whenever empty string umarshaled into json.Number, there won't be any error. On go1.14, the behavior is return error. See https://go-review.googlesource.com/c/go/+/195045/

Summary of changes: create custom unmarshaller for Number.

2021-04-29 01:35 UTC, subosito requested changes

2021-04-29 01:35 UTC, subosito commented on encoding/json/number.go
> +	builtin_json "encoding/json"
yang `builtin_json` ini sebaiknya diganti jadi satu kata mas, `bjson`, atau semacamnya...

2021-04-29 01:35 UTC, subosito commented on encoding/json/number.go
> +	return strconv.ParseFloat(string(n), 64)
Yang ini nanti bisa pakai `return n.Number.Float64()`. `String` dan `Int64` juga sama.

2021-04-29 01:35 UTC, subosito commented on encoding/json/number.go
> +type Number builtin_json.Number
Yang ini sebaiknya pakai `struct` mas, biar ga inherit langsung, misal:

```go
type Number struct {
        bjson.Number
}
```

2021-04-29 02:11 UTC, agriardyan commented on encoding/json/number.go
> +	builtin_json "encoding/json"
Noted mas. Changed yak

2021-04-29 02:11 UTC, agriardyan commented on encoding/json/number.go
> +	return strconv.ParseFloat(string(n), 64)
Updated ya mas

2021-04-29 02:11 UTC, agriardyan commented on encoding/json/number.go
> +type Number builtin_json.Number
Okay mas. Sdh sy update

2021-04-29 03:01 UTC, pascalmail commented on encoding/json/number_test.go
> +func TestNumber_invalid(t *testing.T) {
Untuk test, mungkin bisa pakai pendekatan [Table Driven Test](https://github.com/golang/go/wiki/TableDrivenTests), untuk memudahkan kita melihat apa input dan apa ekspektasi outputnya.

2021-04-29 03:35 UTC, agriardyan commented on encoding/json/number_test.go
> +func TestNumber_invalid(t *testing.T) {
Good sugesstion. Sy implement dulu

2021-04-29 03:49 UTC, subosito approved these changes

2021-04-30 01:36 UTC, subosito requested changes

2021-04-30 01:36 UTC, subosito commented on encoding/json/number.go
>  	if strB == "" || strB == "null" {
ini bisa di compare dengan:

```go
if strB == `""` || strB == "null" {
```

sehingga line atasnya bisa diubah jadi `strB := string(b)`

2021-04-30 01:36 UTC, subosito commented on encoding/json/number.go
> +	if !isValidNumber(strB) {
ini bisa dihapus mas, biar fallback ke json unmarshal bawah..

2021-04-30 01:53 UTC, agriardyan commented on encoding/json/number.go
> +	if !isValidNumber(strB) {
Berarti kalau inputnya bukan number behaviornya tetap pass ya mas?

2021-04-30 02:15 UTC, agriardyan commented on encoding/json/number.go
>  	if strB == "" || strB == "null" {
Setuju dengan `if strB == `""` || strB == "null"`
Tapi kalau strings.Trim nya dihilangkan, nanti ketika ketemu value spt {"something": "3"}, strB akan menjadi \"3\"

2021-04-30 02:23 UTC, agriardyan commented on encoding/json/number_test.go
> +func TestNumber_invalid(t *testing.T) {
Done ya

2021-04-30 02:38 UTC, subosito commented on encoding/json/number.go
>  	if strB == "" || strB == "null" {
kalau original behaviournya seperti apa mas? yang penting original behaviournya tetep dijaga.. karena yang mau di handle kan empty string saja..

2021-04-30 02:38 UTC, subosito commented on encoding/json/number.go
>  	if strB == "" || strB == "null" {
original behaviour `json.Number`

2021-04-30 03:14 UTC, subosito commented on encoding/json/number.go
>  	if strB == "" || strB == "null" {
barusan saya cek behaviournya beda mas.. https://gist.github.com/subosito/4e32cd154706ff7cd94a6f42bf5b7e56

2021-04-30 03:52 UTC, pascalmail commented on encoding/json/number.go
> +	if !isValidNumber(strB) {
Karena behaviour yg berubah itu terkait handling empty string, cukup yg itu saja yg ditambah. Selain itu defer ke implementasi `encoding/json` saja.

2021-04-30 04:42 UTC, agriardyan commented on encoding/json/number.go
>  	if strB == "" || strB == "null" {
Updated mas

2021-04-30 04:43 UTC, agriardyan commented on encoding/json/number.go
> +	if !isValidNumber(strB) {
Updated mas

2021-04-30 08:18 UTC, subosito requested changes

2021-04-30 08:18 UTC, subosito commented on encoding/json/number.go
> +	if strB == `""` || strB == "null" {
yang condition `strB == "null"` bisa dihapus mas, fallback aja ke original

2021-04-30 08:18 UTC, subosito commented on encoding/json/number.go
> +func (v *Number) MarshalJSON() ([]byte, error) {
Untuk `MarshalJSON` ini sebaiknya langsung pakai aja yang original mas.. 

```go
func (v Number) MarshalJSON() ([]byte, error) {
        s := bjson.Number(v)
        return bjson.Marshal(s)
}
```

2021-04-30 08:18 UTC, subosito commented on encoding/json/number.go
> +func (v Number) String() string { return string(v) }
Yang `String`, `Float64` dan `Int64` bisa dihapus aja mas, kita butuhnya custom json marshaler aja soalnya..

2021-04-30 08:40 UTC, agriardyan commented on encoding/json/number.go
> +func (v Number) String() string { return string(v) }
updated ya mas

2021-04-30 08:46 UTC, subosito approved these changes

2021-04-30 09:55 UTC, merged